### ISSUE TITLE
For Loop Program Error

### ISSUE THREAD

**Issue by iamMubasharYasin** [iamMubasharYasin/Cpp-Programs#1]
My for loop Program [Program](https://github.com/iamMubasharYasin/Cpp-Programs/blob/main/forloop.cpp) is not working properly can anyone fix this issue for me please.

**Comment by HammadMaqbool** [comment]
Ok I will solve this issue for you.

**Comment by iamMubasharYasin** [comment]
> Ok I will solve this issue for you.

Thanks I will wait for your PR
